### ISSUE TITLE
Problem with changing the texture of a soda can

### ISSUE THREAD

**Issue by MutiniMatthew** [SeymourSchlong/CustomMugsAndCans#1]
Hello, I'm trying to make a mod for my friends and customize mugs and soda cans. 
I replaced the texture of the mug (CoffeeMugTex 1.png) and it worked, but replacing the texture of the soda (Red soda.png) had no effect. What am I doing wrong, or maybe a different approach is needed here? (I tested the presence of an image on objects using the item spawner)
I would also like to take this opportunity to ask if other mods are planned to replace textures?

**Comment by SeymourSchlong** [comment]
turns out i wrote `RedSodaCan` instead of `SodaCanRed`, whoops! i'll update it soon with a fix

i dont have any scrap planned in particular, but if you have any you'd want to see i wouldnt mind taking a look!

**Comment by MutiniMatthew** [comment]
I'm glad to hear it! And about the scrap, I would like to see a custom Toy Robot, Large Axle, V-type engine and Masks (if possible, because their textures are quite complex, it seems to me)
I don't mind trying to customize the scrap myself, but I don't understand this thing at all. I will be glad of any tip on how to do it myself, so as not to bother you :)

**Comment by SeymourSchlong** [comment]
idk what zeekerss did when making the UVs but it is horrendous to work with outside of Blender

i can upload the source code for the custom mugs here, but getting the proper texture and model is a mildly annoying process

i used [Asset Ripper](https://github.com/AssetRipper/AssetRipper/releases) to extract stuff from the game, then i found the proper texture and mesh, imported the mesh into Unity and extracted it as a .FBX file, and finally put it all into Blender where you can easily just draw right on top of the model.
